In [1]:
#Import library
import numpy as np
import sys

In [14]:
#Data
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
#Get Dimension
a.ndim

1

In [5]:
#Explaination
#Dimension (chiều) đề cập đến số lượng trục (axes) mà một mảng NumPy (ndarray) có.
#Bạn có thể hiểu mỗi chiều như một cách để bạn có thể di chuyển qua các phần tử của mảng.

In [7]:
#Get shape
b.shape

(2, 3)

In [15]:
#Get type
a.dtype

dtype('int32')

In [20]:
#Get size
a.itemsize
#b.itemsize #Float will 8

4

In [18]:
#Get total size
a.nbytes #a.size * a.itemsize

12

In [23]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [24]:
#Get a specific element [r, c]
a[1, 5]
#Explaination
#-----------------------------------------------------------------------
#       | Cột 0 | Cột 1 | Cột 2 | Cột 3 | Cột 4 | Cột 5 | Cột 6 |
#----------------------------------------------------------------------
# Hàng 0|   1   |   2   |   3   |   4   |   5   |   6   |   7   |
#-----------------------------------------------------------------------
# Hàng 1|   8   |   9   |   10   |   11   |   12   |   13   |   14   |
#a[1, 5] means row 0 and column 5 which is 13

np.int64(13)

In [31]:
#Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [29]:
#Get a specific column
a[:, 2]

array([ 3, 10])

In [33]:
#Getting a little fancy [startindex:endindex:stepsize]
a[0, 1:-2:2]

array([2, 4])

In [35]:
a[1,5] = 20
print(a)

a[1,2] = 5
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  3  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [40]:
 b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
 print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [42]:
b[0,1,1]
#The result is 4 because choose the first block, first row and first column

np.int64(4)

In [44]:
b[:,0,0]
#: means both

array([1, 5])

In [45]:
#replace
b[:,1,:] = [[9,9],[8,8]]